### ISSUE TITLE
CGAdd command get rejected

### ISSUE THREAD

**Issue by super-ienien** [SuperFlyTV/casparcg-connection#21] opened 2016-10-27 20:32 UTC
Hi,

Sorry, it's me again. I updated casparcg-connection to the last version in order to get the CGInvoke command correction.

Now, the promise returned by cgAdd are rejected. I didn't change anything in my code.

I can give you some infos : 

my code that send the command wher `this.cg` is the CasparCG instance :  

```
loadScene(scene)
{
    this.currentScene = scene;
    scene = 'MISS-REVEAL-'+scene;
    return this.cg.cgAdd(1,1,1, scene, true);
}
```

the object passed to the rejection (converted in JSON) : 

```
{
  "response": {},
  "responseProtocol": {
    "code": 202,
    "parser": null
  },
  "_status": 5,
  "_payload": {
    "flashLayer": {
      "key": "ADD",
      "value": 1
    },
    "templateName": {
      "key": "",
      "value": "\"MISS-REVEAL-2\""
    },
    "playOnLoad": {
      "key": "",
      "value": 1
    }
  },
  "_stringParamsArray": [],
  "_objectParams": {
    "channel": 1,
    "layer": 1,
    "flashLayer": 1,
    "templateName": "MISS-REVEAL-2",
    "playOnLoad": true
  },
  "_channel": 1,
  "_layer": 1,
  "paramProtocol": [
    {
      "name": "flashLayer",
      "key": "ADD",
      "payload": 1,
      "validation": {
        "resolved": true,
        "_min": 0,
        "_max": null
      }
    },
    {
      "name": "templateName",
      "key": null,
      "payload": "\"MISS-REVEAL-2\"",
      "validation": {
        "resolved": true
      }
    },
    {
      "name": "playOnLoad",
      "key": null,
      "payload": 1,
      "validation": {
        "resolved": true,
        "_valueOnSuccess": 1,
        "_valueOnFail": 0
      }
    },
    {
      "name": "data",
      "key": null,
      "payload": null,
      "validation": {
        "resolved": false
      }
    }
  ]
}
```

the caspar server log : 

```
Accepted connection from 127.0.0.1 3
[2016-10-27 22:11:30.128] [13328] [info]    Received message from 127.0.0.1: CG 1-1 ADD 1 "MISS-REVEAL-2" 1\r\n
[2016-10-27 22:11:30.140] [11924] [info]    flash[cg20.fth.pal|5000] Invoking add-command: <invoke name="Add" returntype="xml"><arguments><number>1</number><string>MISS-REVEAL-2.ft</string><true/><string></string><string><![CDATA[ ]]></string></arguments></invoke>
[2016-10-27 22:11:30.244] [14564] [debug]   flash-player[cg20.fth.pal|1024x576] [command]      <invoke name="OnCommand" returntype="xml"><arguments><string>Command recieved @GetInfo@?@</string></arguments></invoke>
[2016-10-27 22:11:30.258] [14564] [info]    flash-player[cg20.fth.pal|1024x576] Initialized.
[2016-10-27 22:11:30.260] [14564] [debug]   flash-player[cg20.fth.pal|1024x576] [command]      <invoke name="OnCommand" returntype="xml"><arguments><string>Command recieved @Add@1@</string></arguments></invoke>
[2016-10-27 22:11:30.458] [14564] [debug]   flash-player[cg20.fth.pal|1024x576] [activity]     <invoke name="OnActivity" returntype="xml"><arguments><string>Command finished @Add@1@</string></arguments></invoke>
[2016-10-27 22:11:30.622] [14564] [debug]   flash-player[cg20.fth.pal|1024x576] [activity]     <invoke name="OnActivity" returntype="xml"><arguments><string>Command finished @Play@1@</string></arguments></invoke>
[2016-10-27 22:11:30.725] [13104] [debug]   Executed command: CGCommand
[2016-10-27 22:11:30.729] [13104] [info]    Sent message to 127.0.0.1: 202 CG OK\r\n
```

**Comment by super-ienien** [comment] 2016-10-27 20:35
In the JSON representation of the command we can see that the status is set to 5, wich if we follow the source code means "failed". But casparCg sent a 202 CG OK response...

This is why I think something bad si hapenning here :)

**Comment by jesperstarkar** [comment] 2016-10-27 20:36
Yes, sorry about that.

I was a bit too quick last night, merged in some old stuff on the dev-branch which probably had breaking changes.

I can't fix this tonight, so the easiest thing for you is to roll back to .8.4 and manually change the single line of code in CasparCG.ts/js from removeCommand to invokeCommand as a workaround.

I will look into this, it is probably one of the validators/parsers thats's not implemented yet. It will then reject the promise even if the command is correctly executed by CasparCG.

**Comment by super-ienien** [comment] 2016-10-27 20:37
ok thanks a lot ! good night

**Comment by jesperstarkar** [comment] 2016-10-27 20:38
Wait a second, CGAdd and not ADD you say? Strange. It should work, as I am currently using this from .9.1 myself. Let me have a quick look.

**Comment by jesperstarkar** [comment] 2016-10-27 20:46
Reject wil FAILED can only occur if the responseValidator fails, and in the last-minute-dodgy-code I implemented in .9 yesterday for solving another problem, related to loss of connection or timeout in responses.

The strange thing is I'm running .9.1 here as we speak with no such problem.

**Comment by jesperstarkar** [comment] 2016-10-27 20:55
Sorry super-ienien, I can't look into this tonight. I have to come back to it.

As a workaround I propose you roll back and patch up the single line of code needed for Invoke.

**Comment by super-ienien** [comment] 2016-10-27 20:57
Yes,

I try to look if i didn't make a mistake between my fork of casparcg-connection and your .9.1 version. But I do not find anything.

Don't be sorry. And thanks a lot for answering me so quickly. I will roll back and patch.

Thanks again

**Comment by jesperstarkar** [comment] 2016-10-27 20:59
As you can tell from the code in general, we are a bit away from V1 and a solid solution. But I love stating to have feedback and users. Gives motivation and inspiration. 

And we have used ccg-con in production since .1, but in very isolated environments and with thorough manual testing.

**Comment by super-ienien** [comment] 2016-10-27 21:06
don't worry. Your work is amazing. It makes very easy to work with casparcg and NodeJS ! I don't use your library in production now, i am testing it in a new project that I'm working on. If it works I will put it in production very soon.

**Comment by jesperstarkar** [comment] 2016-10-27 21:19
I don't think your "response" object should be empty. That might be a clue.

**Comment by super-ienien** [comment] 2016-10-27 21:21
Don't worry it can wait :) 

I patched the .8.4 everything is working now.

**Comment by jesperstarkar** [comment] 2016-11-30 17:29
Hi again @super-ienien. Sorry, I cant reproduce this. Are you sure your template-name was right? What respons do you get in the CasparCG log from this command?

**Comment by jesperstarkar** [comment] 2016-12-21 21:16
I would love if you could try version 0.12 @super-ienien, I will be surprised if you still have the same problem.

**Comment by super-ienien** [comment] 2016-12-21 23:52
Sorry Jesper, I didn't have time to look into this. I will use caspar-connection in my next project so I will let you know if I get this error again. Thanks again for this great work. Caspar-connection is very useful.

**Comment by super-ienien** [comment] 2016-12-21 23:55
In fact I will test it now

**Comment by super-ienien** [comment] 2016-12-22 00:06
Great ! the issue is gone with 0.12.1

Thanks !

**Comment by jesperstarkar** [comment] 2016-12-22 09:50
Thank you!

**Closed by jesperstarkar** 2016-12-22 09:50 UTC
Labels: bug
